name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.3", "8.4", "8.5" ]
        dependencies: [ "lowest", "highest" ]

    name: PHP ${{ matrix.php-version }} - ${{ matrix.dependencies }} deps

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run test suite
        run: vendor/bin/phpunit
